### ISSUE TITLE
Contribution: db2mon for windows - powershell

### ISSUE THREAD

**Issue by sampizarro** [IBM/db2-samples#17]
Hi Team

first of all,  Congratulation is opening db2-samples to the community. !!! 

I was planning to convert db2mon.sh  to powershell,  so this useful tool could also be used on windows environments.. 

I am also an IBMer, and you can reach me at pizarros@br.ibm.com

**Comment by kdrodger** [comment]
Thanks @sampizarro .  We're delighted to have this out in the public realm and looking forward to your contributions!

Regarding that particular script, portability is vitally important as it is also frequently used in Linux and UNIX environments so please keep that in mind.  If we can have one tool that works everywhere that is certainly best, although we there is some limited precedent for a small number of platform specific tools.

**Comment by sampizarro** [comment]
Well

sorry, but the original script was designed in shell-script (bash).  so it was already designed not to be portable, when first created by ibm.  Was intended only to be used for UNIX/Linux environment. 

My suggestion is to have a new one,  made in powershell,  doing exactly the same thing the unix one is doing today..  so  Unix guys would still using the original db2mon.sh one ,  and windows users could use the new powershell version   db2mon.ps1   

that was my proposal. . 

Keep in mind that you have this same approach in several others samples scripts..  
a .sh one for unix,  and a .bat (old windows batch cmd line)  for windows... 

Please let me know if this would be a feasible approach.

**Comment by qpresley** [comment]
Closing this issue as the PR was merged.
