### ISSUE TITLE
What do those files, "bldapp" "bldmc" "bldrtn", do?

### ISSUE THREAD

**Issue by xmduhan** [IBM/db2-samples#44]
What do those files, "bldapp" "bldmc" "bldrtn"  (in the path db2-samples/cli/), do?
how can I rewrite the makefile just use gcc?

**Comment by kdrodger** [comment]
As described within the comments of each, they are examples of how to build applications.  There's also some more elaborate descriptions in the associated README ( https://github.com/IBM/db2-samples/blob/master/cli/README ).

`bldapp` : Builds a linux application (using gcc)
https://github.com/IBM/db2-samples/blob/8f9229235ca24885cfebde131a80abdc3c84c6ef/cli/bldapp#L22

`bldmc` : Builds a multi-connection app, utilizing connections to multiple databases
https://github.com/IBM/db2-samples/blob/8f9229235ca24885cfebde131a80abdc3c84c6ef/cli/bldmc#L22

`bldrtn` : Builds a routine, a stored procedure or user defined function
https://github.com/IBM/db2-samples/blob/8f9229235ca24885cfebde131a80abdc3c84c6ef/cli/bldrtn#L22

They're all relatively similar if you compare their source, with some subtle differences for those specific purposes.

Hope that helps.

**Comment by xmduhan** [comment]
Thank you!
