### ISSUE TITLE
Can't find COM.ibm.db2.app.*;  

### ISSUE THREAD

**Issue by xinyuliu12** [IBM/db2-samples#47]
Hello,

I am trying to write my own Java UDFs. But it looks like the `COM.ibm.db2.app` dependency is missing.
Can you please provide pointers on where I can download it?

Sincerely,
Xinyu
![image](https://user-images.githubusercontent.com/23177234/171422462-002f7714-09c1-4f7c-a8fe-9d396701f62d.png)

**Comment by kdrodger** [comment]
Have you see the documentation on building Java routines?  Let me know if that's helpful, or not.

https://www.ibm.com/docs/en/db2/11.5?topic=routines-creating-java

**Comment by xinyuliu12** [comment]
Thank you so much for the quick reply! I will take a look at it.
