### ISSUE TITLE
NameError: name 'pandas' is not defined

### ISSUE THREAD

**Issue by junsulee75** [IBM/db2-samples#8]
When running this notebook on my python 3.7 environment, I encountered the following error

`---> 14 wine = pandas.read_sql(sql,hdbi)
..
NameError: name 'pandas' is not defined`

Changing the relevant lines like below, it worked fine.
`#wine = pandas.read_sql(sql,hdbi)
wine = pd.read_sql(sql,hdbi)`

I guess that is because we declared in the start of code
`import pandas as pd
`
Posting this just in case we need to change it.

**Comment by kdrodger** [comment]
Thanks for the feedback @junsulee75 .  You're welcome to submit a PR to propose that change yourself, otherwise I'll try to get that corrected later today or tomorrow.

**Comment by junsulee75** [comment]
Hello Kelly, Thank you for the change.
